import Main from './components/Main'
import Head from 'next/head'
import About from './components/About'
import Contact from './components/Contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Trade-App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="" /> */}
      </Head>
      <Main />
      <About/>
      
      <Contact/>
    </div>
  )
}
